### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by seanfcarroll** [sveltejs/awesome#18]
Cool project.

Is it just me, or is all the code on the [example site](https://svelte.technology/repl?version=1.64.1&demo=svg-clock) not working?

<img width="516" alt="screen shot 2018-11-17 at 17 32 43" src="https://user-images.githubusercontent.com/11340230/48663335-03d03600-ea8f-11e8-94c9-8c108e956137.png">
<img width="1012" alt="screen shot 2018-11-17 at 17 32 29" src="https://user-images.githubusercontent.com/11340230/48663336-0468cc80-ea8f-11e8-8245-ce80e56fc256.png">
<img width="885" alt="screen shot 2018-11-17 at 17 32 18" src="https://user-images.githubusercontent.com/11340230/48663337-0468cc80-ea8f-11e8-8aad-2575f773413a.png">

**Comment by Conduitry** [comment]
(Trying out github's new 'transfer issue feature! Looks like it's working)

The sveltejs/awesome repo could definitely use some updating. I'm imagining that's where these links were from.

**Comment by Conduitry** [comment]
It looks like #10 is intended to address this? I'm taking a look at that PR

**Comment by Conduitry** [comment]
Polished up the PR and merged it. I think this issue should be all set now.

However, we definitely ought to put a bit more effort into this repo. Keeping this up-to-date is not really on anyone's radar, unfortunately.

**Comment by Conduitry** [comment]
@seanfcarroll I'm curious, where you bumped into the link to this repo from? It's not well maintained, and - I thought - not linked to from many places.

**Comment by seanfcarroll** [comment]
Working now!
